# Generated by Django 2.2.10 on 2020-03-17 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOtherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_openid', models.CharField(max_length=64, null=True, unique=True, verbose_name='微信唯一标识')),
                ('wx_session_key', models.CharField(max_length=64, null=True, verbose_name='微信会话秘钥')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='绑定用户')),
            ],
        ),
        migrations.CreateModel(
            name='UserWxInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=32, null=True, verbose_name='用户昵称')),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')])),
                ('country', models.CharField(max_length=32, null=True, verbose_name='用户所在国家')),
                ('province', models.CharField(max_length=32, null=True, verbose_name='用户所在省份')),
                ('city', models.CharField(max_length=32, null=True, verbose_name='用户所在城市')),
                ('language', models.CharField(choices=[('en', '英文'), ('zh_CN', '简体中文'), ('zh_TW', '繁体中文')], max_length=8, null=True, verbose_name='语言')),
                ('avatarUrl', models.URLField(null=True, verbose_name='头像链接')),
                ('other_info', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wx_info', to='UserManager.UserOtherInfo')),
            ],
        ),
    ]
