# Generated by Django 2.2.10 on 2020-03-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Memo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='has_completed',
            new_name='checked',
        ),
        migrations.RenameField(
            model_name='memo',
            old_name='data',
            new_name='content',
        ),
        migrations.AddField(
            model_name='memo',
            name='author_id',
            field=models.IntegerField(default=1, verbose_name='作者id'),
            preserve_default=False,
        ),
    ]
