# Generated by Django 2.2.10 on 2020-03-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Memo', '0002_auto_20200317_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='author_id',
        ),
        migrations.AddField(
            model_name='memo',
            name='author_name',
            field=models.CharField(default=1, max_length=128, verbose_name='作者账户名'),
            preserve_default=False,
        ),
    ]
