# Generated by Django 2.2.10 on 2020-03-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Memo', '0003_auto_20200317_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='is_actived',
            field=models.BooleanField(default=True),
        ),
    ]
